#pragma once

UENUM(BlueprintType)
enum EBattleState : uint8
{
    BATTLE_STATE_WAIT_ACTION,
    BATTLE_STATE_PLAYER_ACTION_SELECT,
    BATTLE_STATE_PLAYER_SELECT_ENEMY_TARGET,
    BATTLE_STATE_PLAYER_SELECT_ALL_ENEMY_TARGETS,
    BATTLE_STATE_PLAYER_SELECT_ALLY_TARGET,
    BATTLE_STATE_PLAYER_SELECT_ALL_ALLY_TARGETS,
    BATTLE_STATE_PLAYER_SELECT_ANY_TARGET,
    BATTLE_STATE_PLAYER_SELECT_ALL_TARGETS,
    BATTLE_STATE_PLAYER_SELECT_ATTACK,
    BATTLE_STATE_PLAYER_SELECT_SPELL
};