#pragma once

UENUM(BlueprintType)
enum ECombatStatus : uint8
{
  COMBAT_STATUS_HP,
  COMBAT_STATUS_CURRENT_HP,
  COMBAT_STATUS_MANA,
  COMBAT_STATUS_CURRENT_MANA,
  COMBAT_STATUS_PHYSICAL_DAMAGE,
  COMBAT_STATUS_PHYSICAL_DEFENSE,
  COMBAT_STATUS_MAGIC_DAMAGE,
  COMBAT_STATUS_MAGIC_DEFENSE,
  COMBAT_STATUS_STAMINA,
  COMBAT_STATUS_CURRENT_STAMINA,
  COMBAT_STATUS_SPEED,
  COMBAT_STATUS_EVASION
};